sulu_form:
    mail:
        from: "%env(SULU_ADMIN_EMAIL)%"
        to: "%env(SULU_ADMIN_EMAIL)%"
        sender: "%env(SULU_ADMIN_EMAIL)%"
        templates:
            notify: 'mails/dynamic-notify.html.twig'
            notify_plain_text: 'mails/dynamic-notify-plain-text.html.twig'
            customer: 'mails/success_kontakt.html.twig'
            customer_plain_text: 'mails/success_kontakt-plain-text.html.twig'
    media:
        protected: true

framework:
    esi: true
    fragments: true
