version: '3.1'

services:

    database:
        image: mysql:5.7
        restart: always

        environment:
            - MYSQL_PASSWORD=k1l2a3u4s
            - MYSQL_ROOT_PASSWORD=k1l2a3u4s
            - MYSQL_DATABASE=diebasis-mysql

        volumes:
            - ./var/db-data:/var/lib/mysql:rw

        ports:
            - 3306:3306